name: latex-compile-release
run-name: ${{ github.actor }} is learning GitHub Actions

on: [workflow_dispatch, push]

jobs:
  main:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout repository
          uses: actions/checkout@v5
        - name: Compile LaTeX
          uses: xu-cheng/latex-action@v3
          with:
            root_file: |
              **/*.tex
        - name: Create folder 
          run: mkdir pdfs
        - name: Copy compiled pdfs to folder
          run: cp *.pdf pdfs
        - name: Inspect contents
          run: ls -R .
        - name: Create release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref_name }}
            release_name: Release ${{ github.ref_name }}
        - name: Inspecting release output
          run: cat ${{ steps.create_release.output }}