name: latex-compile-release
run-name: ${{ github.actor }} is learning GitHub Actions

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Hello World
          run: echo "Hello world"